//home
export const LOGIN = "home/LOGIN"
export const LOGIN_SUCCESS = "home/LOGIN_SUCCESS"
export const LOGIN_FAIL = "home/LOGIN_FAIL"
export const PREPARE_USER_UPDATE = "home/PREPARE_USER_UPDATE"
export const UPDATE_USER = "home/UPDATE_USER"
export const UPDATE_USER_SUCCESS = "home/UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "home/UPDATE_USER_FAIL"
export const LOGOUT = "home/LOGOUT"
export const CONSENT_LOADED = "home/CONSENT_LOADED"
export const SET_CONSENT = "home/SET_CONSENT"
export const UNSET_CONSENT = "home/UNSET_CONSENT"
export const SET_LANGUAGE = "home/SET_LANGUAGE"

//discs
export const PREPARE_GET_DISC = "discs/PREPARE_GET"
export const PREPARE_EDIT_DISC = "discs/PREPARE_EDIT"
export const GET_DISCS = "discs/GET"
export const GET_DISCS_SUCCESS = "discs/GET_SUCCESS"
export const GET_DISCS_FAIL = "discs/GET_FAIL"
export const GET_DISCS_NEXT_PAGE = "discs/GET_NEXT_PAGE"
export const GET_DISCS_NEXT_PAGE_SUCCESS = "discs/GET_NEXT_PAGE_SUCCESS"
export const GET_DISCS_NEXT_PAGE_FAIL = "discs/GET_NEXT_PAGE_FAIL"
export const UPDATE_DISC = "discs/UPDATE"
export const UPDATE_DISC_SUCCESS = "discs/UPDATE_SUCCESS"
export const UPDATE_DISC_FAIL = "discs/UPDATE_FAIL"
export const CREATE_DISC = "discs/CREATE"
export const CREATE_DISC_SUCCESS = "discs/CREATE_SUCCESS"
export const CREATE_DISC_FAIL = "discs/CREATE_FAIL"
export const PREPARE_CREATE_DISC = "discs/PREPARE_CREATE"
export const DELETE_DISC = "discs/DELETE"
export const DELETE_DISC_SUCCESS = "discs/DELETE_SUCCESS"
export const DELETE_DISC_FAIL = "discs/DELETE_FAIL"
export const UPDATE_IMAGE = "discs/UPDATE_IMAGE"
export const UPDATE_IMAGE_SUCCESS = "discs/UPDATE_IMAGE_SUCCESS"
export const UPDATE_IMAGE_FAIL = "discs/UPDATE_IMAGE_FAIL"

//dropdowns
export const GET_DROPDOWNS = "dropdowns/GET"
export const GET_DROPDOWNS_SUCCESS = "dropdowns/GET_SUCCESS"
export const GET_DROPDOWNS_FAIL = "dropdowns/GET_FAIL"
